apiVersion: v1
kind: Pod
metadata:
  name: config-secret-demo-pod
spec:
  containers:
  - name: demo-container
    image: busybox:1.36
    command: [ "sh", "-c", "env && sleep 3600" ]
    env:
      - name: APP_ENV
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: APP_ENV
      - name: APP_COLOR
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: APP_COLOR
      - name: WELCOME_MSG
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: WELCOME_MSG
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: DB_USER
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: DB_PASSWORD
